# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 80)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_resolucion = QtWidgets.QLabel(self.centralwidget)
        self.label_resolucion.setGeometry(QtCore.QRect(20, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resolucion.setFont(font)
        self.label_resolucion.setObjectName("label_resolucion")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 270, 120))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_content_resolucion = QtWidgets.QLabel(self.frame)
        self.label_content_resolucion.setGeometry(QtCore.QRect(120, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_content_resolucion.setFont(font)
        self.label_content_resolucion.setStyleSheet("color: rgb(0, 134, 0);")
        self.label_content_resolucion.setObjectName("label_content_resolucion")
        self.label_x = QtWidgets.QLabel(self.frame)
        self.label_x.setGeometry(QtCore.QRect(40, 50, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_x.setFont(font)
        self.label_x.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_x.setObjectName("label_x")
        self.label_contentx = QtWidgets.QLabel(self.frame)
        self.label_contentx.setGeometry(QtCore.QRect(70, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_contentx.setFont(font)
        self.label_contentx.setObjectName("label_contentx")
        self.label_contenty = QtWidgets.QLabel(self.frame)
        self.label_contenty.setGeometry(QtCore.QRect(180, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_contenty.setFont(font)
        self.label_contenty.setObjectName("label_contenty")
        self.label_y = QtWidgets.QLabel(self.frame)
        self.label_y.setGeometry(QtCore.QRect(150, 50, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_y.setFont(font)
        self.label_y.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_y.setObjectName("label_y")
        self.frame.raise_()
        self.label_resolucion.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "M POINTER"))
        self.label_resolucion.setText(_translate("MainWindow", "Resolucion"))
        self.label_content_resolucion.setText(_translate("MainWindow", "x,y"))
        self.label_x.setText(_translate("MainWindow", "X:"))
        self.label_contentx.setText(_translate("MainWindow", "111"))
        self.label_contenty.setText(_translate("MainWindow", "111"))
        self.label_y.setText(_translate("MainWindow", "Y:"))
